apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-host
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-host
  template:
    metadata:
      labels:
        app: mysql-host
    spec:
      containers:
        - name: mysql-host
          image: mysql:8
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "password"
            - name: MYSQL_USER
              value: "user"
            - name: MYSQL_PASSWORD
              value: "password"
            - name: MYSQL_DATABASE
              value: "dbname"
          ports:
            - containerPort: 3306
